Chap7 edits
LaunchCodeEducation/lchs pull request #23
Opened 2020-09-02 14:54 UTC by CarlyLanglois

2020-09-03 01:03 UTC, jimflores5 requested changes
Carly, good edits!  I think this time there's only one comment that doesn't involve small typo fixes or minor word changes.

2020-09-03 21:32 UTC, CarlyLanglois commented on src/chapters/strings/more-on-brackets.rst
> +   Given ``language = 'Python'``, what does ``language[1:5]`` return?
ytho is some well known meme text so its a fun easter egg

2020-09-03 21:32 UTC, CarlyLanglois commented on src/chapters/strings/string-conditionals.rst
> +   So a string that comes earlier in the alphabet is considered *less than* a string that comes
referring to Unicode here doesnt do harm in my eyes. this explanation doesnt ask them to get familiar with unicode and use it, but rather to know that this is the system responsible for the result of the comparison

2020-09-03 21:32 UTC, CarlyLanglois commented on src/chapters/strings/string-immutability.rst
> +   string, but we are not. Instead, we just replace the old, unchanged string
there's a not in all caps in the code block just below this. like exclamation points, too many too frequently dilutes the impact

2020-09-03 21:32 UTC, CarlyLanglois commented on src/chapters/strings/template-literals.rst
> +	Make it readable.
i honestly thought you wrote a little poem here. The principles are good but i don't think we need to promote someone's dissociated distillation of a religious tenet, even if it is widely accepted within the python community. I just removed the section

2020-09-03 22:20 UTC, jimflores5 commented on src/chapters/strings/more-on-brackets.rst
> +   Given ``language = 'Python'``, what does ``language[1:5]`` return?
Ah.  I'll have to Google that.

2020-09-04 14:08 UTC, jimflores5 commented on src/chapters/strings/string-immutability.rst
> +   string, but we are not. Instead, we just replace the old, unchanged string
OK.  I see.

2020-09-04 14:20 UTC, jimflores5 commented on src/chapters/strings/string-conditionals.rst
> +   So a string that comes earlier in the alphabet is considered *less than* a string that comes
OK.  However, we can make this more clear if we explicitly state that a Unicode value is a number.

"...character's Unicode value, which is a number given to all symbols, letters, etc."  

Then, in the last sentence, we can reinforce this with "...earlier in the alphabet has a lower Unicode value, so it is *less than*..."

2020-09-09 17:31 UTC, jimflores5 requested changes
Carly, we're almost there!

2020-09-09 17:31 UTC, jimflores5 commented on src/chapters/strings/string-conditionals.rst
> +   So a string that comes earlier in the alphabet is considered *less than* a string that comes
I'm still struggling with this paragraph.

I see the new reference to the Unicode section, but the text there talks about special symbols and non-Latin characters.  Can we insert a simple mention here about Unicode relating to numerical values?

We don't have to go into anything like 0x0042 <---> 66 <---> "B", but helping the kids see that letters relate to numbers will clarify how the comparisons work.

2020-09-10 15:52 UTC, jimflores5 commented on src/chapters/strings/string-conditionals.rst
> +   So a string that comes earlier in the alphabet is considered *less than* a string that comes
I just kept getting hung up on "Unicode values" not clicking in the students' brains as being comparable. Calling then numbers and giving the link to the interactive table helps.

2020-09-11 20:46 UTC, merged